name: Build & Deploy CloudStream Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.13

      - name: Build Extensions
        run: gradle make

      - name: Prepare builds folder
        run: |
          mkdir -p builds
          cp repo.json builds/
          cp WowUncutProvider/build/WowUncutProvider.cs3 builds/
          echo '[{"name":"WowUncut","pluginType":"PROVIDER","url":"https://raw.githubusercontent.com/senkuboy0-cyber/WowUncutProvider/builds/WowUncutProvider.cs3","version":1,"internalName":"WowUncutProvider","authors":["senkuboy0-cyber"],"description":"WowUncut Web Series","repositoryUrl":"https://github.com/senkuboy0-cyber/WowUncutProvider","language":"hi","tvTypes":["TvSeries","Movie","Others"]}]' > builds/plugins.json

      - name: Deploy to builds branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: builds
          folder: builds
          clean: true
